---
# There is no point installing the banner unless sshd is present.
- name: Install openssh-server
  ansible.builtin.package:
    name: openssh-server

- name: Install motd file
  ansible.builtin.copy:
    dest: /etc/motd
    mode: 0644
    src: motd

- name: Install issue file
  ansible.builtin.copy:
    dest: /etc/issue
    mode: 0644
    src: issue

- name: Enable banner in sshd
  ansible.builtin.lineinfile:
    backrefs: yes
    dest: /etc/ssh/sshd_config
    line: "Banner /etc/issue"
    regexp: "^.?Banner"
    state: present
