# tasks file for banner

# This is required temporarily, because of
# https://github.com/ansible/ansible/issues/56583
- name: Temporary workaround for ansible/ansible#56583
  set_fact:
    ansible_facts:
      pkg_mgr: yum
  when: ansible_os_family == "RedHat" and ansible_distribution == "Amazon"
# This is already installed on the AMIs we use, but not on the Docker
# images we use for our molecule tests
- name: Install openssh-server
  package:
    name: openssh-server

- name: Install motd file
  copy:
    src: motd
    dest: /etc/motd

- name: Install issue file
  copy:
    src: issue
    dest: /etc/issue

- name: Enable banner in sshd
  lineinfile:
    dest: /etc/ssh/sshd_config
    line: "Banner /etc/issue"
    regexp: "^.?Banner"
    state: present
    backrefs: yes
