---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: amazonlinux2
    image: amazonlinux:2
  - name: debian9
    image: debian:stretch-slim
    dockerfile: Dockerfile_debian_9.j2
  - name: debian10
    image: debian:buster-slim
  - name: debian11
    image: debian:bullseye-slim
  - name: kali
    image: kalilinux/kali-rolling
  - name: fedora32
    image: fedora:32
  - name: fedora33
    image: fedora:33
  - name: ubuntu16
    image: ubuntu:xenial
  - name: ubuntu18
    image: ubuntu:bionic
provisioner:
  name: ansible
  config_options:
    defaults:
      # The OS family and distribution for Kali is "Kali GNU/Linux",
      # which is not an allowable group name in Ansible due to the
      # space and the slash.  This option converts those characters to
      # underscores when creating the group name.
      force_valid_group_names: always
scenario:
  name: default
verifier:
  name: testinfra
